theme: minimal-mistakes-jekyll
title: 麦丽素
locale: "en-US"
description: >- # this means to ignore newlines until "baseurl:"
  A place for notes on various topics.
baseurl: "/hackmd-note" # the subpath of your site, e.g. /blog
url: "https://favormylikes.github.io"
github_username:  FavorMylikes

plugins:
  - jekyll-katex

markdown: kramdown
kramdown:
  math_engine: katex
  math_engine_opts: {}
katex: