# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme : "minimal-mistakes-jekyll"
# remote_theme : "mmistakes/minimal-mistakes"
minimal_mistakes_skin : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Site Settings
title: 麦丽素
locale: "en-US"
description: >- # this means to ignore newlines until "baseurl:"
  A place for notes on various topics.
baseurl: "/hackmd-note" # the subpath of your site, e.g. /blog
url: "https://favormylikes.github.io"
github_username:  FavorMylikes

paginate: 5 # amount of posts to show
paginate_path: /hackmd-note/page:num/

plugins:
  # - kramdown-math-katex
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: katex
  math_engine_opts: {}
katex: