# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme : "minimal-mistakes-jekyll"
# remote_theme : "mmistakes/minimal-mistakes"
minimal_mistakes_skin : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Site Settings
title: Notes
title_separator : "/"
subtitle : "麦"
locale: "en-US"
description: >- # this means to ignore newlines until "baseurl:"
  A place for notes on various topics.
baseurl: "/hackmd-note" # the subpath of your site, e.g. /blog
url: "https://favormylikes.github.io"
github_username:  FavorMylikes

paginate: 5 # amount of posts to show
paginate_path: /hackmd-note/page:num/

plugins:
  # - kramdown-math-katex
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      katex: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true    

markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: katex
  math_engine_opts: {}
katex: