# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme : "minimal-mistakes-jekyll"
# remote_theme : "mmistakes/minimal-mistakes"
minimal_mistakes_skin : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Site Settings
author: "麦丽素"
title: "Notes B"
title_separator : "/"
subtitle : "麦丽素的日常"
locale: "en-US"
description: >- # this means to ignore newlines until "baseurl:"
  A place for notes on various topics.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ucas.io/"
github_username:  FavorMylikes
timezone: Asia/Shanghai
logo: "https://raw.githubusercontent.com/FavorMylikes/hackmd-note/img/imgucas_logo.png"

# jekyll-algolia
search_provider: algolia
  application_id: 7UHEFEG9HB
  index_name: prod_UCAS_IO
  search_only_api_key: b1cdde9827760050f51383c6c78127bf
  powered_by: # true (default), false

# jekyll-archives
permalink: /:categories/:title/
breadcrumbs: true  # disabled by default

# jykell Paginate 
paginate_path: '/blog/:num/'
pagination: # jekyll-paginate-v2
  enabled: true
  debug: true  # open debug
  per_page: 5
  permalink: '/blog/:num/'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

plugins:
  # - kramdown-math-katex
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      date_format: "%Y-%m-%d"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      katex: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: null  # default is mathjax, see here https://kramdown.gettalong.org/options.html#option-math-engine
  # math_engine_opts: {}
katex:
