remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have o
title: [My Blog]
description: [My daily note at UCAS]
destination: ./build